// +build ignore

package jclass

// https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.1-200-E.1
type ClassAccessFlag uint16

const (
	// Declared public; may be accessed from outside its package.
	ACC_PUBLIC ClassAccessFlag = 0x0001
	// Declared final; no subclasses allowed.
	ACC_FINAL = 0x0010
	// Treat superclass methods specially when invoked by the invokespecial instruction.
	ACC_SUPER = 0x0020
	// Is an interface, not a class.
	ACC_INTERFACE = 0x0200
	// Declared abstract; must not be instantiated.
	ACC_ABSTRACT = 0x0400
	// Declared synthetic; not present in the source code.
	ACC_SYNTHETIC = 0x1000
	// Declared as an annotation type.
	ACC_ANNOTATION = 0x2000
	// Declared as an enum type.
	ACC_ENUM = 0x4000
)

// https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.5-200-A.1
type FieldAccessFlag uint16

const (
	// Declared public; may be accessed from outside its package.
	ACC_PUBLIC FieldAccessFlag = 0x0001
	// Declared private; usable only within the defining class.
	ACC_PRIVATE = 0x0002
	// Declared protected; may be accessed within subclasses.
	ACC_PROTECTED = 0x0004
	// Declared static.
	ACC_STATIC = 0x0008
	// Declared final; never directly assigned to after object construction (JLS §17.5).
	ACC_FINAL = 0x0010
	// Declared volatile; cannot be cached.
	ACC_VOLATILE = 0x0040
	// Declared transient; not written or read by a persistent object manager.
	ACC_TRANSIENT = 0x0080
	// Declared synthetic; not present in the source code.
	ACC_SYNTHETIC = 0x1000
	// Declared as an element of an enum.
	ACC_ENUM = 0x4000
)

// https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.6-200-A.1
type MethodAccessFlag uint16

const (
	// Declared public; may be accessed from outside its package.
	ACC_PUBLIC MethodAccessFlag = 0x0001
	// Declared private; accessible only within the defining class.
	ACC_PRIVATE = 0x0002
	// Declared protected; may be accessed within subclasses.
	ACC_PROTECTED = 0x0004
	// Declared static.
	ACC_STATIC = 0x0008
	// Declared final; must not be overridden (§5.4.5).
	ACC_FINAL = 0x0010
	// Declared synchronized; invocation is wrapped by a monitor use.
	ACC_SYNCHRONIZED = 0x0020
	// A bridge method, generated by the compiler.
	ACC_BRIDGE = 0x0040
	// Declared with variable number of arguments.
	ACC_VARARGS = 0x0080
	// Declared native; implemented in a language other than Java.
	ACC_NATIVE = 0x0100
	// Declared abstract; no implementation is provided.
	ACC_ABSTRACT = 0x0400
	// Declared strictfp; floating-point mode is FP-strict.
	ACC_STRICT = 0x0800
	// Declared synthetic; not present in the source code.
	ACC_SYNTHETIC = 0x1000
)

// https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4-140
type ConstantPoolTag uint8

const (
	CONSTANT_Class              ConstantPoolTag = 7
	CONSTANT_Fieldref                           = 9
	CONSTANT_Methodref                          = 10
	CONSTANT_InterfaceMethodref                 = 11
	CONSTANT_String                             = 8
	CONSTANT_Integer                            = 3
	CONSTANT_Float                              = 4
	CONSTANT_Long                               = 5
	CONSTANT_Double                             = 6
	CONSTANT_NameAndType                        = 12
	CONSTANT_Utf8                               = 1
	CONSTANT_MethodHandle                       = 15
	CONSTANT_MethodType                         = 16
	CONSTANT_InvokeDynamic                      = 18
)
